import type { CompanyAlert, CompanyClient, CompanyKpi, CompanyTrendPoint } from '../types'

export const companyKpis: CompanyKpi[] = [
  { label: 'Clientes ativos', value: '24', hint: '+3 no trimestre' },
  { label: 'MRR consolidado', value: 'R$ 148.000', hint: 'Receita recorrente mensal' },
  { label: 'Deployments saudáveis', value: '21', hint: '87,5% da base' },
  { label: 'Licenças consumidas', value: '73%', hint: 'Média geral da operação' },
]

export const companyAlerts: CompanyAlert[] = [
  {
    id: 'alt-1',
    title: 'Instabilidade de deployment',
    clientName: 'Prefeitura de Campinas',
    severity: 'Alta',
    description: 'A instância apresentou aumento de erro 5xx nas últimas 2 horas.',
  },
  {
    id: 'alt-2',
    title: 'Licença próxima do limite',
    clientName: 'Coleta Verde Ambiental',
    severity: 'Média',
    description: 'Uso de sensores licenciados atingiu 92% da capacidade contratada.',
  },
  {
    id: 'alt-3',
    title: 'Renovação contratual próxima',
    clientName: 'Prefeitura de Sorocaba',
    severity: 'Baixa',
    description: 'Contrato vence em 18 dias e exige contato comercial.',
  },
]

export const companyTrend: CompanyTrendPoint[] = [
  { label: 'Jan', clients: 12, revenue: 76000 },
  { label: 'Fev', clients: 15, revenue: 92000 },
  { label: 'Mar', clients: 17, revenue: 108000 },
  { label: 'Abr', clients: 19, revenue: 121000 },
  { label: 'Mai', clients: 21, revenue: 134000 },
  { label: 'Jun', clients: 24, revenue: 148000 },
]

export const companyClients: CompanyClient[] = [
  {
    id: '46395000000139',
    slug: 'prefeitura-sao-paulo',
    name: 'Prefeitura de São Paulo',
    type: 'Prefeitura',
    status: 'Ativo',
    city: 'São Paulo',
    state: 'SP',
    plan: 'Enterprise',
    activatedAt: '2026-01-12',
    monthlyRevenue: 42000,
    activeUsers: 186,
    monitoredBins: 1240,
    collectionEfficiency: 94,
    licenseUsage: 81,
    deploymentStatus: 'Online',
    version: 'v2.8.1',
    uptime: '99.98%',
    contractEndsAt: '2027-01-12',
    internalOwner: 'Juan Andrade',
  },
  {
    id: '69597457000155',
    slug: 'prefeitura-campinas',
    name: 'Prefeitura de Campinas',
    type: 'Prefeitura',
    status: 'Atenção',
    city: 'Campinas',
    state: 'SP',
    plan: 'Pro',
    activatedAt: '2025-10-04',
    monthlyRevenue: 18000,
    activeUsers: 73,
    monitoredBins: 540,
    collectionEfficiency: 88,
    licenseUsage: 77,
    deploymentStatus: 'Degradado',
    version: 'v2.7.4',
    uptime: '98.91%',
    contractEndsAt: '2026-10-04',
    internalOwner: 'Mauricio Ferreira',
  },
  {
    id: '001',
    slug: 'ecotrack-demo',
    name: 'EcoTrack Demo',
    type: 'Empresa de coleta',
    status: 'Onboarding',
    city: 'Pouso Alegre',
    state: 'MG',
    plan: 'Basic',
    activatedAt: '2026-04-01',
    monthlyRevenue: 6000,
    activeUsers: 14,
    monitoredBins: 96,
    collectionEfficiency: 79,
    licenseUsage: 62,
    deploymentStatus: 'Online',
    version: 'v2.8.1',
    uptime: '99.40%',
    contractEndsAt: '2027-04-01',
    internalOwner: 'Caio Mattos',
  },
  {
    id: '88421009000120',
    slug: 'coleta-verde-ambiental',
    name: 'Coleta Verde Ambiental',
    type: 'Empresa de coleta',
    status: 'Ativo',
    city: 'Ribeirão Preto',
    state: 'SP',
    plan: 'Pro',
    activatedAt: '2025-08-19',
    monthlyRevenue: 14000,
    activeUsers: 38,
    monitoredBins: 320,
    collectionEfficiency: 90,
    licenseUsage: 92,
    deploymentStatus: 'Online',
    version: 'v2.8.0',
    uptime: '99.82%',
    contractEndsAt: '2026-08-19',
    internalOwner: 'Nelson Sousa',
  },
]
